### ISSUE TITLE
'usb' module not found

### ISSUE THREAD

**Issue by EmbeddedTony** [SoulCipher/shofel2_linux#10]
Traceback (most recent call last):
  File "./shofel2.py", line 8, in <module>
    import usb.core
ModuleNotFoundError: No module named 'usb'

Running on ubuntu, I have pip and pyusb and python installed but it still says that there is no usb module, thx in advance.

**Comment by cdumars** [comment]
i had a similar issue --
i think "$ sudo python3 -mpip install pyusb" should do the trick

**Comment by EmbeddedTony** [comment]
thx!
