### ISSUE TITLE
struct.error: unpack requires a string argument of length 4

### ISSUE THREAD

**Issue by SuperOkazaki** [SoulCipher/shofel2_linux#2]
Hi,

I have everything downloaded and set up, but when I run it with a Switch connected I am met with `struct.error: unpack requires a string argument of length 4`

This happens with Python3 and Python2.

Ubuntu 16.x

**Comment by Luro02** [comment]
could you please give the full terminal output ?

**Comment by SuperOkazaki** [comment]
The issue was my bad, I was using a 2.0 port that I thought was 3.0 because it was blue.
